/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElTable: (typeof import("element-plus/es"))["ElTable"];
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
    MainContent: (typeof import("./src/components/MainContent.vue"))["default"];
    MainSidebar: (typeof import("./src/components/MainSidebar.vue"))["default"];
    TheTable: (typeof import("./src/components/TheTable.vue"))["default"];
    TheTableBody: (typeof import("./src/components/TheTableBody.vue"))["default"];
    TheTableColumn: (typeof import("./src/components/TheTableColumn.vue"))["default"];
  }
}
